var car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car < 'toyota'? I predict true.");
console.log(car < 'toyota');
console.log("Is car > 'toyota'? I predict false.");
console.log(car > 'toyota');
console.log("Is car <= 'subaru'? I predict true.");
console.log(car <= 'subaru');
console.log("Is car >= 'toyota'? I predict false.");
console.log(car >= 'toyota');
